// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package curriculumsql

import (
	"time"

	"github.com/google/uuid"
)

type ArticleAttachment struct {
	ID          uuid.UUID
	ArticleID   uuid.UUID
	Filename    string
	ContentType string
	SizeBytes   int64
	StorageKey  string
	CreatedAt   time.Time
}

type Group struct {
	ID uuid.UUID
}

type Lesson struct {
	ID              uuid.UUID
	ModuleID        uuid.UUID
	Title           string
	Position        int32
	DurationSeconds *int32
	CreatedAt       time.Time
}

type Module struct {
	ID          uuid.UUID
	Title       string
	Description string
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
}

type Ticket struct {
	ID        uuid.UUID
	VariantID uuid.UUID
	TopicID   uuid.UUID
}

type TicketAttempt struct {
	ID        uuid.UUID
	VariantID uuid.UUID
	UserID    uuid.UUID
	Status    string
}

type Topic struct {
	ID        uuid.UUID
	Title     string
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

type TopicArticle struct {
	ID        uuid.UUID
	TopicID   uuid.UUID
	Title     string
	BodyMd    string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID uuid.UUID
}

type UserModule struct {
	UserID        uuid.UUID
	ModuleID      uuid.UUID
	AssignedBy    uuid.UUID
	SourceGroupID *uuid.UUID
	AssignedAt    time.Time
}

type Variant struct {
	ID        uuid.UUID
	LessonID  uuid.UUID
	Title     string
	Position  int32
	CreatedAt time.Time
}
