// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package curriculumsql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearPrimaryVariants = `-- name: ClearPrimaryVariants :exec
UPDATE variants SET is_primary = false WHERE lesson_id = $1
`

func (q *Queries) ClearPrimaryVariants(ctx context.Context, lessonID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryVariants, lessonID)
	return err
}

const countLessonsByModule = `-- name: CountLessonsByModule :one
SELECT COUNT(*)::int AS count FROM lessons WHERE module_id = $1 AND archived_at IS NULL
`

func (q *Queries) CountLessonsByModule(ctx context.Context, moduleID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countLessonsByModule, moduleID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countTicketsByLesson = `-- name: CountTicketsByLesson :one
SELECT COUNT(*)::int AS count
FROM tickets t
JOIN variants v ON v.id = t.variant_id
WHERE v.lesson_id = $1
`

func (q *Queries) CountTicketsByLesson(ctx context.Context, lessonID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countTicketsByLesson, lessonID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countVariantsByLesson = `-- name: CountVariantsByLesson :one
SELECT COUNT(*)::int AS count FROM variants WHERE lesson_id = $1
`

func (q *Queries) CountVariantsByLesson(ctx context.Context, lessonID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countVariantsByLesson, lessonID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :exec
INSERT INTO topic_articles (id, topic_id, title, body_md, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateArticleParams struct {
	ID        uuid.UUID
	TopicID   uuid.UUID
	Title     string
	BodyMd    string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) error {
	_, err := q.db.Exec(ctx, createArticle,
		arg.ID,
		arg.TopicID,
		arg.Title,
		arg.BodyMd,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO article_attachments (id, article_id, filename, content_type, size_bytes, storage_key, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAttachmentParams struct {
	ID          uuid.UUID
	ArticleID   uuid.UUID
	Filename    string
	ContentType string
	SizeBytes   int64
	StorageKey  string
	CreatedAt   time.Time
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.Exec(ctx, createAttachment,
		arg.ID,
		arg.ArticleID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.CreatedAt,
	)
	return err
}

const createLesson = `-- name: CreateLesson :exec
INSERT INTO lessons (id, module_id, title, position, duration_seconds, archived_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateLessonParams struct {
	ID              uuid.UUID
	ModuleID        uuid.UUID
	Title           string
	Position        int32
	DurationSeconds *int32
	ArchivedAt      *time.Time
	CreatedAt       time.Time
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) error {
	_, err := q.db.Exec(ctx, createLesson,
		arg.ID,
		arg.ModuleID,
		arg.Title,
		arg.Position,
		arg.DurationSeconds,
		arg.ArchivedAt,
		arg.CreatedAt,
	)
	return err
}

const createModule = `-- name: CreateModule :exec
INSERT INTO modules (id, title, description, status, success_threshold, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateModuleParams struct {
	ID               uuid.UUID
	Title            string
	Description      string
	Status           string
	SuccessThreshold int32
	CreatedBy        uuid.UUID
	CreatedAt        time.Time
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) error {
	_, err := q.db.Exec(ctx, createModule,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.SuccessThreshold,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const createTopic = `-- name: CreateTopic :exec
INSERT INTO topics (id, title, created_by, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateTopicParams struct {
	ID        uuid.UUID
	Title     string
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) error {
	_, err := q.db.Exec(ctx, createTopic,
		arg.ID,
		arg.Title,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const createVariant = `-- name: CreateVariant :exec
INSERT INTO variants (id, lesson_id, title, position, status, is_primary, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateVariantParams struct {
	ID        uuid.UUID
	LessonID  uuid.UUID
	Title     string
	Position  int32
	Status    string
	IsPrimary bool
	CreatedAt time.Time
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) error {
	_, err := q.db.Exec(ctx, createVariant,
		arg.ID,
		arg.LessonID,
		arg.Title,
		arg.Position,
		arg.Status,
		arg.IsPrimary,
		arg.CreatedAt,
	)
	return err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM topic_articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM article_attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const deleteLesson = `-- name: DeleteLesson :exec
DELETE FROM lessons WHERE id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLesson, id)
	return err
}

const deleteModule = `-- name: DeleteModule :exec
DELETE FROM modules WHERE id = $1
`

func (q *Queries) DeleteModule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteModule, id)
	return err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const deleteVariant = `-- name: DeleteVariant :exec
DELETE FROM variants WHERE id = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariant, id)
	return err
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, topic_id, title, body_md, created_by, created_at, updated_at
FROM topic_articles
WHERE id = $1
`

func (q *Queries) GetArticleByID(ctx context.Context, id uuid.UUID) (TopicArticle, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i TopicArticle
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Title,
		&i.BodyMd,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, article_id, filename, content_type, size_bytes, storage_key, created_at
FROM article_attachments
WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id uuid.UUID) (ArticleAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i ArticleAttachment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, module_id, title, position, duration_seconds, archived_at, created_at
FROM lessons
WHERE id = $1
`

func (q *Queries) GetLessonByID(ctx context.Context, id uuid.UUID) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLessonByID, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Position,
		&i.DurationSeconds,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLessonByVariant = `-- name: GetLessonByVariant :one
SELECT l.id, l.module_id, l.title, l.position, l.duration_seconds, l.archived_at, l.created_at
FROM lessons l
JOIN variants v ON v.lesson_id = l.id
WHERE v.id = $1
`

func (q *Queries) GetLessonByVariant(ctx context.Context, id uuid.UUID) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLessonByVariant, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Position,
		&i.DurationSeconds,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getModuleByID = `-- name: GetModuleByID :one
SELECT id, title, description, status, success_threshold, created_by, created_at
FROM modules
WHERE id = $1
`

func (q *Queries) GetModuleByID(ctx context.Context, id uuid.UUID) (Module, error) {
	row := q.db.QueryRow(ctx, getModuleByID, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.SuccessThreshold,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, title, created_by, created_at
FROM topics
WHERE id = $1
`

func (q *Queries) GetTopicByID(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByID, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserModule = `-- name: GetUserModule :one
SELECT user_id, module_id, assigned_by, source_group_id, assigned_at
FROM user_modules
WHERE user_id = $1 AND module_id = $2
`

type GetUserModuleParams struct {
	UserID   uuid.UUID
	ModuleID uuid.UUID
}

func (q *Queries) GetUserModule(ctx context.Context, arg GetUserModuleParams) (UserModule, error) {
	row := q.db.QueryRow(ctx, getUserModule, arg.UserID, arg.ModuleID)
	var i UserModule
	err := row.Scan(
		&i.UserID,
		&i.ModuleID,
		&i.AssignedBy,
		&i.SourceGroupID,
		&i.AssignedAt,
	)
	return i, err
}

const getVariantByID = `-- name: GetVariantByID :one
SELECT id, lesson_id, title, position, status, is_primary, created_at
FROM variants
WHERE id = $1
`

func (q *Queries) GetVariantByID(ctx context.Context, id uuid.UUID) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariantByID, id)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.Title,
		&i.Position,
		&i.Status,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const hasUserModule = `-- name: HasUserModule :one
SELECT EXISTS(
    SELECT 1 FROM user_modules WHERE user_id = $1 AND module_id = $2
) AS exists
`

type HasUserModuleParams struct {
	UserID   uuid.UUID
	ModuleID uuid.UUID
}

func (q *Queries) HasUserModule(ctx context.Context, arg HasUserModuleParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserModule, arg.UserID, arg.ModuleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listArticlesByTopic = `-- name: ListArticlesByTopic :many
SELECT id, topic_id, title, body_md, created_by, created_at, updated_at
FROM topic_articles
WHERE topic_id = $1
ORDER BY created_at
`

func (q *Queries) ListArticlesByTopic(ctx context.Context, topicID uuid.UUID) ([]TopicArticle, error) {
	rows, err := q.db.Query(ctx, listArticlesByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopicArticle{}
	for rows.Next() {
		var i TopicArticle
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Title,
			&i.BodyMd,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByArticle = `-- name: ListAttachmentsByArticle :many
SELECT id, article_id, filename, content_type, size_bytes, storage_key, created_at
FROM article_attachments
WHERE article_id = $1
ORDER BY created_at
`

func (q *Queries) ListAttachmentsByArticle(ctx context.Context, articleID uuid.UUID) ([]ArticleAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArticleAttachment{}
	for rows.Next() {
		var i ArticleAttachment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsByModule = `-- name: ListLessonsByModule :many
SELECT id, module_id, title, position, duration_seconds, archived_at, created_at
FROM lessons
WHERE module_id = $1 AND archived_at IS NULL
ORDER BY position, created_at
`

func (q *Queries) ListLessonsByModule(ctx context.Context, moduleID uuid.UUID) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.Title,
			&i.Position,
			&i.DurationSeconds,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonsPool = `-- name: ListLessonsPool :many
SELECT id, module_id, title, position, duration_seconds, archived_at, created_at
FROM lessons
WHERE archived_at IS NULL
AND ($1::text IS NULL OR $1::text = '' OR title ILIKE '%' || $1::text || '%')
ORDER BY created_at DESC
`

func (q *Queries) ListLessonsPool(ctx context.Context, q_ pgtype.Text) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsPool, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.Title,
			&i.Position,
			&i.DurationSeconds,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModules = `-- name: ListModules :many
SELECT id, title, description, status, success_threshold, created_by, created_at
FROM modules
ORDER BY created_at DESC
`

func (q *Queries) ListModules(ctx context.Context) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.SuccessThreshold,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModulesFiltered = `-- name: ListModulesFiltered :many
SELECT id, title, description, status, success_threshold, created_by, created_at
FROM modules
WHERE (
    $1::text IS NULL OR $1::text = ''
    OR title ILIKE '%' || $1::text || '%'
    OR description ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL OR $2::text = '' OR $2::text = 'all'
    OR ($2::text = 'active' AND status = 'active')
    OR ($2::text = 'draft' AND status = 'draft')
    OR ($2::text = 'archived' AND status = 'archived')
    OR ($2::text = 'mine' AND created_by = $3::uuid)
    OR ($2::text = 'team' AND created_by <> $3::uuid AND status <> 'archived')
)
ORDER BY created_at DESC
`

type ListModulesFilteredParams struct {
	Q       pgtype.Text
	Scope   pgtype.Text
	ActorID pgtype.UUID
}

func (q *Queries) ListModulesFiltered(ctx context.Context, arg ListModulesFilteredParams) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModulesFiltered, arg.Q, arg.Scope, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.SuccessThreshold,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicIDsForUser = `-- name: ListTopicIDsForUser :many
SELECT DISTINCT t.topic_id
FROM tickets t
JOIN ticket_attempts a ON a.variant_id = t.variant_id
WHERE a.user_id = $1 AND t.variant_id IS NOT NULL
`

func (q *Queries) ListTopicIDsForUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTopicIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var topic_id uuid.UUID
		if err := rows.Scan(&topic_id); err != nil {
			return nil, err
		}
		items = append(items, topic_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopics = `-- name: ListTopics :many
SELECT id, title, created_by, created_at
FROM topics
ORDER BY created_at
`

func (q *Queries) ListTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsByModule = `-- name: ListUserIDsByModule :many
SELECT user_id FROM user_modules WHERE module_id = $1
`

func (q *Queries) ListUserIDsByModule(ctx context.Context, moduleID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserIDsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserModules = `-- name: ListUserModules :many
SELECT user_id, module_id, assigned_by, source_group_id, assigned_at
FROM user_modules
WHERE user_id = $1
ORDER BY assigned_at
`

func (q *Queries) ListUserModules(ctx context.Context, userID uuid.UUID) ([]UserModule, error) {
	rows, err := q.db.Query(ctx, listUserModules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserModule{}
	for rows.Next() {
		var i UserModule
		if err := rows.Scan(
			&i.UserID,
			&i.ModuleID,
			&i.AssignedBy,
			&i.SourceGroupID,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserModulesByModule = `-- name: ListUserModulesByModule :many
SELECT user_id, module_id, assigned_by, source_group_id, assigned_at
FROM user_modules
WHERE module_id = $1
`

func (q *Queries) ListUserModulesByModule(ctx context.Context, moduleID uuid.UUID) ([]UserModule, error) {
	rows, err := q.db.Query(ctx, listUserModulesByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserModule{}
	for rows.Next() {
		var i UserModule
		if err := rows.Scan(
			&i.UserID,
			&i.ModuleID,
			&i.AssignedBy,
			&i.SourceGroupID,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByLesson = `-- name: ListVariantsByLesson :many
SELECT id, lesson_id, title, position, status, is_primary, created_at
FROM variants
WHERE lesson_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListVariantsByLesson(ctx context.Context, lessonID uuid.UUID) ([]Variant, error) {
	rows, err := q.db.Query(ctx, listVariantsByLesson, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variant{}
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Title,
			&i.Position,
			&i.Status,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :exec
UPDATE topic_articles SET title = $2, body_md = $3, updated_at = $4 WHERE id = $1
`

type UpdateArticleParams struct {
	ID        uuid.UUID
	Title     string
	BodyMd    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) error {
	_, err := q.db.Exec(ctx, updateArticle,
		arg.ID,
		arg.Title,
		arg.BodyMd,
		arg.UpdatedAt,
	)
	return err
}

const updateLesson = `-- name: UpdateLesson :exec
UPDATE lessons SET title = $2, position = $3, duration_seconds = $4, archived_at = $5 WHERE id = $1
`

type UpdateLessonParams struct {
	ID              uuid.UUID
	Title           string
	Position        int32
	DurationSeconds *int32
	ArchivedAt      *time.Time
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) error {
	_, err := q.db.Exec(ctx, updateLesson,
		arg.ID,
		arg.Title,
		arg.Position,
		arg.DurationSeconds,
		arg.ArchivedAt,
	)
	return err
}

const updateModule = `-- name: UpdateModule :exec
UPDATE modules SET title = $2, description = $3, status = $4, success_threshold = $5 WHERE id = $1
`

type UpdateModuleParams struct {
	ID               uuid.UUID
	Title            string
	Description      string
	Status           string
	SuccessThreshold int32
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) error {
	_, err := q.db.Exec(ctx, updateModule,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.SuccessThreshold,
	)
	return err
}

const updateTopic = `-- name: UpdateTopic :exec
UPDATE topics SET title = $2 WHERE id = $1
`

type UpdateTopicParams struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) error {
	_, err := q.db.Exec(ctx, updateTopic, arg.ID, arg.Title)
	return err
}

const updateVariant = `-- name: UpdateVariant :exec
UPDATE variants SET title = $2, position = $3, status = $4, is_primary = $5 WHERE id = $1
`

type UpdateVariantParams struct {
	ID        uuid.UUID
	Title     string
	Position  int32
	Status    string
	IsPrimary bool
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) error {
	_, err := q.db.Exec(ctx, updateVariant,
		arg.ID,
		arg.Title,
		arg.Position,
		arg.Status,
		arg.IsPrimary,
	)
	return err
}

const upsertUserModule = `-- name: UpsertUserModule :exec
INSERT INTO user_modules (user_id, module_id, assigned_by, source_group_id, assigned_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, module_id) DO UPDATE SET
    assigned_by = EXCLUDED.assigned_by,
    source_group_id = EXCLUDED.source_group_id,
    assigned_at = EXCLUDED.assigned_at
`

type UpsertUserModuleParams struct {
	UserID        uuid.UUID
	ModuleID      uuid.UUID
	AssignedBy    uuid.UUID
	SourceGroupID *uuid.UUID
	AssignedAt    time.Time
}

func (q *Queries) UpsertUserModule(ctx context.Context, arg UpsertUserModuleParams) error {
	_, err := q.db.Exec(ctx, upsertUserModule,
		arg.UserID,
		arg.ModuleID,
		arg.AssignedBy,
		arg.SourceGroupID,
		arg.AssignedAt,
	)
	return err
}
