// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package callssql

import (
	"time"

	"github.com/google/uuid"
)

type AttemptCall struct {
	ID         uuid.UUID
	AttemptID  uuid.UUID
	TicketID   uuid.UUID
	UserID     uuid.UUID
	ScenarioID string
	BankDigest string
	ChannelID  string
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type CallTurn struct {
	ID        int64
	CallID    uuid.UUID
	N         int32
	Utterance string
	Reply     string
	Style     string
	CreatedAt time.Time
}
