// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package callssql

import (
	"context"

	"github.com/google/uuid"
)

const activeCallForAttempt = `-- name: ActiveCallForAttempt :one
SELECT id, attempt_id, ticket_id, user_id, scenario_id, bank_digest, channel_id, status, created_at, updated_at
FROM attempt_calls WHERE attempt_id = $1
 AND status IN ('originating','ringing','answered','completed')
 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) ActiveCallForAttempt(ctx context.Context, attemptID uuid.UUID) (AttemptCall, error) {
	row := q.db.QueryRow(ctx, activeCallForAttempt, attemptID)
	var i AttemptCall
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.TicketID,
		&i.UserID,
		&i.ScenarioID,
		&i.BankDigest,
		&i.ChannelID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCall = `-- name: CreateCall :exec
INSERT INTO attempt_calls (id, attempt_id, ticket_id, user_id, scenario_id, bank_digest, channel_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateCallParams struct {
	ID         uuid.UUID
	AttemptID  uuid.UUID
	TicketID   uuid.UUID
	UserID     uuid.UUID
	ScenarioID string
	BankDigest string
	ChannelID  string
	Status     string
}

func (q *Queries) CreateCall(ctx context.Context, arg CreateCallParams) error {
	_, err := q.db.Exec(ctx, createCall,
		arg.ID,
		arg.AttemptID,
		arg.TicketID,
		arg.UserID,
		arg.ScenarioID,
		arg.BankDigest,
		arg.ChannelID,
		arg.Status,
	)
	return err
}

const getCallByID = `-- name: GetCallByID :one
SELECT id, attempt_id, ticket_id, user_id, scenario_id, bank_digest, channel_id, status, created_at, updated_at
FROM attempt_calls WHERE id = $1
`

func (q *Queries) GetCallByID(ctx context.Context, id uuid.UUID) (AttemptCall, error) {
	row := q.db.QueryRow(ctx, getCallByID, id)
	var i AttemptCall
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.TicketID,
		&i.UserID,
		&i.ScenarioID,
		&i.BankDigest,
		&i.ChannelID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCallsByAttempt = `-- name: ListCallsByAttempt :many
SELECT id, attempt_id, ticket_id, user_id, scenario_id, bank_digest, channel_id, status, created_at, updated_at
FROM attempt_calls WHERE attempt_id = $1 ORDER BY created_at
`

func (q *Queries) ListCallsByAttempt(ctx context.Context, attemptID uuid.UUID) ([]AttemptCall, error) {
	rows, err := q.db.Query(ctx, listCallsByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptCall{}
	for rows.Next() {
		var i AttemptCall
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.TicketID,
			&i.UserID,
			&i.ScenarioID,
			&i.BankDigest,
			&i.ChannelID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCallChannelID = `-- name: SetCallChannelID :exec
UPDATE attempt_calls SET channel_id = $2, updated_at = now() WHERE id = $1
`

type SetCallChannelIDParams struct {
	ID        uuid.UUID
	ChannelID string
}

func (q *Queries) SetCallChannelID(ctx context.Context, arg SetCallChannelIDParams) error {
	_, err := q.db.Exec(ctx, setCallChannelID, arg.ID, arg.ChannelID)
	return err
}

const setCallStatus = `-- name: SetCallStatus :exec
UPDATE attempt_calls SET status = $2, updated_at = now() WHERE id = $1
`

type SetCallStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetCallStatus(ctx context.Context, arg SetCallStatusParams) error {
	_, err := q.db.Exec(ctx, setCallStatus, arg.ID, arg.Status)
	return err
}

const upsertCallTurn = `-- name: UpsertCallTurn :exec
INSERT INTO call_turns (call_id, n, utterance, reply, style)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (call_id, n) DO UPDATE SET utterance = EXCLUDED.utterance, reply = EXCLUDED.reply, style = EXCLUDED.style
`

type UpsertCallTurnParams struct {
	CallID    uuid.UUID
	N         int32
	Utterance string
	Reply     string
	Style     string
}

func (q *Queries) UpsertCallTurn(ctx context.Context, arg UpsertCallTurnParams) error {
	_, err := q.db.Exec(ctx, upsertCallTurn,
		arg.CallID,
		arg.N,
		arg.Utterance,
		arg.Reply,
		arg.Style,
	)
	return err
}
