// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package ticketssql

import (
	"time"

	"github.com/google/uuid"
)

type AttemptAnswer struct {
	AttemptID          uuid.UUID
	TicketID           uuid.UUID
	IncidentTypeCode   *string
	ApplicantLastName  string
	ApplicantFirstName string
	CallerNumber       string
	DictatedNumber     string
	Notes              string
	UpdatedAt          time.Time
}

type AttemptAnswerService struct {
	AttemptID   uuid.UUID
	TicketID    uuid.UUID
	ServiceCode string
}

type AttemptAnswerTag struct {
	AttemptID uuid.UUID
	TicketID  uuid.UUID
	TagCode   string
}

type GroupMember struct {
	GroupID    uuid.UUID
	UserID     uuid.UUID
	MemberRole string
}

type ReferenceAnswerService struct {
	TicketID    uuid.UUID
	ServiceCode string
}

type ReferenceAnswerTag struct {
	TicketID uuid.UUID
	TagCode  string
}

type Ticket struct {
	ID              uuid.UUID
	VariantID       uuid.UUID
	TopicID         uuid.UUID
	Title           string
	Body            string
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
	Scenario        []byte
	ScenarioVersion string
	Reference       []byte
	Mode            string
	Briefing        string
}

type TicketAttempt struct {
	ID         uuid.UUID
	VariantID  uuid.UUID
	UserID     uuid.UUID
	GrantedBy  uuid.UUID
	AttemptNo  int32
	Status     string
	StartedAt  *time.Time
	DeadlineAt *time.Time
	FinishedAt *time.Time
	Score      *int16
	Report     []byte
}

type TicketReferenceAnswer struct {
	TicketID           uuid.UUID
	IncidentTypeCode   string
	ApplicantLastName  string
	ApplicantFirstName string
	CallerNumber       string
	DictatedNumber     string
}

type Topic struct {
	ID uuid.UUID
}

type Variant struct {
	ID uuid.UUID
}
