// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package ticketssql

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AttemptAnswer struct {
	AttemptID          uuid.UUID
	IncidentTypeCode   pgtype.Text
	ApplicantLastName  string
	ApplicantFirstName string
	CallerNumber       string
	DictatedNumber     string
	Notes              string
	UpdatedAt          time.Time
}

type AttemptAnswerService struct {
	AttemptID   uuid.UUID
	ServiceCode string
}

type AttemptAnswerTag struct {
	AttemptID uuid.UUID
	TagCode   string
}

type GroupMember struct {
	GroupID    uuid.UUID
	UserID     uuid.UUID
	MemberRole string
}

type ReferenceAnswerService struct {
	TicketID    uuid.UUID
	ServiceCode string
}

type ReferenceAnswerTag struct {
	TicketID uuid.UUID
	TagCode  string
}

type Ticket struct {
	ID              uuid.UUID
	GroupID         uuid.UUID
	Title           string
	Body            string
	MaxAttempts     *int32
	AvailableFrom   *time.Time
	AvailableUntil  *time.Time
	DurationSeconds *int32
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
}

type TicketAttempt struct {
	ID         uuid.UUID
	TicketID   uuid.UUID
	UserID     uuid.UUID
	AttemptNo  int32
	Status     string
	StartedAt  time.Time
	DeadlineAt *time.Time
	FinishedAt *time.Time
	Score      *int16
}

type TicketReferenceAnswer struct {
	TicketID           uuid.UUID
	IncidentTypeCode   string
	ApplicantLastName  string
	ApplicantFirstName string
	CallerNumber       string
	DictatedNumber     string
}
