// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package ticketssql

import (
	"time"

	"github.com/google/uuid"
)

type AttemptAnswer struct {
	AttemptID          uuid.UUID
	IncidentTypeID     *uuid.UUID
	ApplicantLastName  string
	ApplicantFirstName string
	CallerNumber       string
	DictatedNumber     string
	Notes              string
	UpdatedAt          time.Time
}

type AttemptAnswerService struct {
	AttemptID uuid.UUID
	ServiceID uuid.UUID
}

type AttemptAnswerTag struct {
	AttemptID uuid.UUID
	TagID     uuid.UUID
}

type EmergencyService struct {
	ID    uuid.UUID
	Code  string
	Title string
}

type GroupMember struct {
	GroupID    uuid.UUID
	UserID     uuid.UUID
	MemberRole string
}

type IncidentTag struct {
	ID             uuid.UUID
	IncidentTypeID uuid.UUID
	Code           string
	Title          string
}

type IncidentType struct {
	ID    uuid.UUID
	Code  string
	Title string
}

type ReferenceAnswerService struct {
	TicketID  uuid.UUID
	ServiceID uuid.UUID
}

type ReferenceAnswerTag struct {
	TicketID uuid.UUID
	TagID    uuid.UUID
}

type Ticket struct {
	ID              uuid.UUID
	GroupID         uuid.UUID
	Title           string
	Body            string
	MaxAttempts     *int32
	AvailableFrom   *time.Time
	AvailableUntil  *time.Time
	DurationSeconds *int32
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
}

type TicketAttempt struct {
	ID         uuid.UUID
	TicketID   uuid.UUID
	UserID     uuid.UUID
	AttemptNo  int32
	Status     string
	StartedAt  time.Time
	DeadlineAt *time.Time
	FinishedAt *time.Time
	Score      *int16
}

type TicketReferenceAnswer struct {
	TicketID           uuid.UUID
	IncidentTypeID     uuid.UUID
	ApplicantLastName  string
	ApplicantFirstName string
	CallerNumber       string
	DictatedNumber     string
}
