// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package ticketssql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAttempt = `-- name: CreateAttempt :exec
INSERT INTO ticket_attempts (
    id, variant_id, user_id, granted_by, attempt_no, status,
    started_at, deadline_at, finished_at, score, report
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateAttemptParams struct {
	ID         uuid.UUID
	VariantID  uuid.UUID
	UserID     uuid.UUID
	GrantedBy  uuid.UUID
	AttemptNo  int32
	Status     string
	StartedAt  *time.Time
	DeadlineAt *time.Time
	FinishedAt *time.Time
	Score      *int16
	Report     []byte
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) error {
	_, err := q.db.Exec(ctx, createAttempt,
		arg.ID,
		arg.VariantID,
		arg.UserID,
		arg.GrantedBy,
		arg.AttemptNo,
		arg.Status,
		arg.StartedAt,
		arg.DeadlineAt,
		arg.FinishedAt,
		arg.Score,
		arg.Report,
	)
	return err
}

const createTicket = `-- name: CreateTicket :exec
INSERT INTO tickets (
    id, variant_id, topic_id, title, body, created_by, created_at,
    scenario, scenario_version, mode, briefing
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateTicketParams struct {
	ID              uuid.UUID
	VariantID       uuid.UUID
	TopicID         uuid.UUID
	Title           string
	Body            string
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
	Scenario        []byte
	ScenarioVersion string
	Mode            string
	Briefing        string
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) error {
	_, err := q.db.Exec(ctx, createTicket,
		arg.ID,
		arg.VariantID,
		arg.TopicID,
		arg.Title,
		arg.Body,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.Scenario,
		arg.ScenarioVersion,
		arg.Mode,
		arg.Briefing,
	)
	return err
}

const deleteAttemptAnswerServices = `-- name: DeleteAttemptAnswerServices :exec
DELETE FROM attempt_answer_services WHERE attempt_id = $1 AND ticket_id = $2
`

type DeleteAttemptAnswerServicesParams struct {
	AttemptID uuid.UUID
	TicketID  uuid.UUID
}

func (q *Queries) DeleteAttemptAnswerServices(ctx context.Context, arg DeleteAttemptAnswerServicesParams) error {
	_, err := q.db.Exec(ctx, deleteAttemptAnswerServices, arg.AttemptID, arg.TicketID)
	return err
}

const deleteAttemptAnswerTags = `-- name: DeleteAttemptAnswerTags :exec
DELETE FROM attempt_answer_tags WHERE attempt_id = $1 AND ticket_id = $2
`

type DeleteAttemptAnswerTagsParams struct {
	AttemptID uuid.UUID
	TicketID  uuid.UUID
}

func (q *Queries) DeleteAttemptAnswerTags(ctx context.Context, arg DeleteAttemptAnswerTagsParams) error {
	_, err := q.db.Exec(ctx, deleteAttemptAnswerTags, arg.AttemptID, arg.TicketID)
	return err
}

const deleteReferenceAnswerServices = `-- name: DeleteReferenceAnswerServices :exec
DELETE FROM reference_answer_services WHERE ticket_id = $1
`

func (q *Queries) DeleteReferenceAnswerServices(ctx context.Context, ticketID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReferenceAnswerServices, ticketID)
	return err
}

const deleteReferenceAnswerTags = `-- name: DeleteReferenceAnswerTags :exec
DELETE FROM reference_answer_tags WHERE ticket_id = $1
`

func (q *Queries) DeleteReferenceAnswerTags(ctx context.Context, ticketID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReferenceAnswerTags, ticketID)
	return err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTicket, id)
	return err
}

const findOpenAttempt = `-- name: FindOpenAttempt :one
SELECT id, variant_id, user_id, granted_by, attempt_no, status,
       started_at, deadline_at, finished_at, score, report
FROM ticket_attempts
WHERE variant_id = $1 AND user_id = $2 AND status IN ('available', 'in_progress')
`

type FindOpenAttemptParams struct {
	VariantID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) FindOpenAttempt(ctx context.Context, arg FindOpenAttemptParams) (TicketAttempt, error) {
	row := q.db.QueryRow(ctx, findOpenAttempt, arg.VariantID, arg.UserID)
	var i TicketAttempt
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.UserID,
		&i.GrantedBy,
		&i.AttemptNo,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
		&i.Score,
		&i.Report,
	)
	return i, err
}

const getAttemptAnswer = `-- name: GetAttemptAnswer :one
SELECT attempt_id, ticket_id, incident_type_code, applicant_last_name, applicant_first_name,
       caller_number, dictated_number, notes, updated_at
FROM attempt_answers
WHERE attempt_id = $1 AND ticket_id = $2
`

type GetAttemptAnswerParams struct {
	AttemptID uuid.UUID
	TicketID  uuid.UUID
}

func (q *Queries) GetAttemptAnswer(ctx context.Context, arg GetAttemptAnswerParams) (AttemptAnswer, error) {
	row := q.db.QueryRow(ctx, getAttemptAnswer, arg.AttemptID, arg.TicketID)
	var i AttemptAnswer
	err := row.Scan(
		&i.AttemptID,
		&i.TicketID,
		&i.IncidentTypeCode,
		&i.ApplicantLastName,
		&i.ApplicantFirstName,
		&i.CallerNumber,
		&i.DictatedNumber,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttemptByID = `-- name: GetAttemptByID :one
SELECT id, variant_id, user_id, granted_by, attempt_no, status,
       started_at, deadline_at, finished_at, score, report
FROM ticket_attempts
WHERE id = $1
`

func (q *Queries) GetAttemptByID(ctx context.Context, id uuid.UUID) (TicketAttempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByID, id)
	var i TicketAttempt
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.UserID,
		&i.GrantedBy,
		&i.AttemptNo,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
		&i.Score,
		&i.Report,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT member_role
FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.GroupID, arg.UserID)
	var member_role string
	err := row.Scan(&member_role)
	return member_role, err
}

const getReferenceAnswer = `-- name: GetReferenceAnswer :one
SELECT ticket_id, incident_type_code, applicant_last_name, applicant_first_name,
       caller_number, dictated_number
FROM ticket_reference_answers
WHERE ticket_id = $1
`

func (q *Queries) GetReferenceAnswer(ctx context.Context, ticketID uuid.UUID) (TicketReferenceAnswer, error) {
	row := q.db.QueryRow(ctx, getReferenceAnswer, ticketID)
	var i TicketReferenceAnswer
	err := row.Scan(
		&i.TicketID,
		&i.IncidentTypeCode,
		&i.ApplicantLastName,
		&i.ApplicantFirstName,
		&i.CallerNumber,
		&i.DictatedNumber,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, variant_id, topic_id, title, body, created_by, created_at,
       scenario, scenario_version, reference, mode, briefing
FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.TopicID,
		&i.Title,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Scenario,
		&i.ScenarioVersion,
		&i.Reference,
		&i.Mode,
		&i.Briefing,
	)
	return i, err
}

const hasAnyAttempt = `-- name: HasAnyAttempt :one
SELECT EXISTS(
    SELECT 1 FROM ticket_attempts WHERE variant_id = $1 AND user_id = $2
) AS exists
`

type HasAnyAttemptParams struct {
	VariantID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) HasAnyAttempt(ctx context.Context, arg HasAnyAttemptParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnyAttempt, arg.VariantID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAttemptAnswerService = `-- name: InsertAttemptAnswerService :exec
INSERT INTO attempt_answer_services (attempt_id, ticket_id, service_code) VALUES ($1, $2, $3)
`

type InsertAttemptAnswerServiceParams struct {
	AttemptID   uuid.UUID
	TicketID    uuid.UUID
	ServiceCode string
}

func (q *Queries) InsertAttemptAnswerService(ctx context.Context, arg InsertAttemptAnswerServiceParams) error {
	_, err := q.db.Exec(ctx, insertAttemptAnswerService, arg.AttemptID, arg.TicketID, arg.ServiceCode)
	return err
}

const insertAttemptAnswerTag = `-- name: InsertAttemptAnswerTag :exec
INSERT INTO attempt_answer_tags (attempt_id, ticket_id, tag_code) VALUES ($1, $2, $3)
`

type InsertAttemptAnswerTagParams struct {
	AttemptID uuid.UUID
	TicketID  uuid.UUID
	TagCode   string
}

func (q *Queries) InsertAttemptAnswerTag(ctx context.Context, arg InsertAttemptAnswerTagParams) error {
	_, err := q.db.Exec(ctx, insertAttemptAnswerTag, arg.AttemptID, arg.TicketID, arg.TagCode)
	return err
}

const insertReferenceAnswerService = `-- name: InsertReferenceAnswerService :exec
INSERT INTO reference_answer_services (ticket_id, service_code) VALUES ($1, $2)
`

type InsertReferenceAnswerServiceParams struct {
	TicketID    uuid.UUID
	ServiceCode string
}

func (q *Queries) InsertReferenceAnswerService(ctx context.Context, arg InsertReferenceAnswerServiceParams) error {
	_, err := q.db.Exec(ctx, insertReferenceAnswerService, arg.TicketID, arg.ServiceCode)
	return err
}

const insertReferenceAnswerTag = `-- name: InsertReferenceAnswerTag :exec
INSERT INTO reference_answer_tags (ticket_id, tag_code) VALUES ($1, $2)
`

type InsertReferenceAnswerTagParams struct {
	TicketID uuid.UUID
	TagCode  string
}

func (q *Queries) InsertReferenceAnswerTag(ctx context.Context, arg InsertReferenceAnswerTagParams) error {
	_, err := q.db.Exec(ctx, insertReferenceAnswerTag, arg.TicketID, arg.TagCode)
	return err
}

const listAttemptAnswerServices = `-- name: ListAttemptAnswerServices :many
SELECT service_code FROM attempt_answer_services WHERE attempt_id = $1 AND ticket_id = $2
`

type ListAttemptAnswerServicesParams struct {
	AttemptID uuid.UUID
	TicketID  uuid.UUID
}

func (q *Queries) ListAttemptAnswerServices(ctx context.Context, arg ListAttemptAnswerServicesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listAttemptAnswerServices, arg.AttemptID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var service_code string
		if err := rows.Scan(&service_code); err != nil {
			return nil, err
		}
		items = append(items, service_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptAnswerTags = `-- name: ListAttemptAnswerTags :many
SELECT tag_code FROM attempt_answer_tags WHERE attempt_id = $1 AND ticket_id = $2
`

type ListAttemptAnswerTagsParams struct {
	AttemptID uuid.UUID
	TicketID  uuid.UUID
}

func (q *Queries) ListAttemptAnswerTags(ctx context.Context, arg ListAttemptAnswerTagsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listAttemptAnswerTags, arg.AttemptID, arg.TicketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag_code string
		if err := rows.Scan(&tag_code); err != nil {
			return nil, err
		}
		items = append(items, tag_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptAnswers = `-- name: ListAttemptAnswers :many
SELECT attempt_id, ticket_id, incident_type_code, applicant_last_name, applicant_first_name,
       caller_number, dictated_number, notes, updated_at
FROM attempt_answers
WHERE attempt_id = $1
`

func (q *Queries) ListAttemptAnswers(ctx context.Context, attemptID uuid.UUID) ([]AttemptAnswer, error) {
	rows, err := q.db.Query(ctx, listAttemptAnswers, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptAnswer{}
	for rows.Next() {
		var i AttemptAnswer
		if err := rows.Scan(
			&i.AttemptID,
			&i.TicketID,
			&i.IncidentTypeCode,
			&i.ApplicantLastName,
			&i.ApplicantFirstName,
			&i.CallerNumber,
			&i.DictatedNumber,
			&i.Notes,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsByUser = `-- name: ListAttemptsByUser :many
SELECT id, variant_id, user_id, granted_by, attempt_no, status,
       started_at, deadline_at, finished_at, score, report
FROM ticket_attempts
WHERE user_id = $1
ORDER BY attempt_no
`

func (q *Queries) ListAttemptsByUser(ctx context.Context, userID uuid.UUID) ([]TicketAttempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketAttempt{}
	for rows.Next() {
		var i TicketAttempt
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.UserID,
			&i.GrantedBy,
			&i.AttemptNo,
			&i.Status,
			&i.StartedAt,
			&i.DeadlineAt,
			&i.FinishedAt,
			&i.Score,
			&i.Report,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsByVariantUser = `-- name: ListAttemptsByVariantUser :many
SELECT id, variant_id, user_id, granted_by, attempt_no, status,
       started_at, deadline_at, finished_at, score, report
FROM ticket_attempts
WHERE variant_id = $1 AND user_id = $2
ORDER BY attempt_no
`

type ListAttemptsByVariantUserParams struct {
	VariantID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) ListAttemptsByVariantUser(ctx context.Context, arg ListAttemptsByVariantUserParams) ([]TicketAttempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByVariantUser, arg.VariantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketAttempt{}
	for rows.Next() {
		var i TicketAttempt
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.UserID,
			&i.GrantedBy,
			&i.AttemptNo,
			&i.Status,
			&i.StartedAt,
			&i.DeadlineAt,
			&i.FinishedAt,
			&i.Score,
			&i.Report,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferenceAnswerServices = `-- name: ListReferenceAnswerServices :many
SELECT service_code FROM reference_answer_services WHERE ticket_id = $1
`

func (q *Queries) ListReferenceAnswerServices(ctx context.Context, ticketID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listReferenceAnswerServices, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var service_code string
		if err := rows.Scan(&service_code); err != nil {
			return nil, err
		}
		items = append(items, service_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferenceAnswerTags = `-- name: ListReferenceAnswerTags :many
SELECT tag_code FROM reference_answer_tags WHERE ticket_id = $1
`

func (q *Queries) ListReferenceAnswerTags(ctx context.Context, ticketID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listReferenceAnswerTags, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag_code string
		if err := rows.Scan(&tag_code); err != nil {
			return nil, err
		}
		items = append(items, tag_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByVariant = `-- name: ListTicketsByVariant :many
SELECT id, variant_id, topic_id, title, body, created_by, created_at,
       scenario, scenario_version, reference, mode, briefing
FROM tickets
WHERE variant_id = $1
ORDER BY created_at
`

func (q *Queries) ListTicketsByVariant(ctx context.Context, variantID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByVariant, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.TopicID,
			&i.Title,
			&i.Body,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Scenario,
			&i.ScenarioVersion,
			&i.Reference,
			&i.Mode,
			&i.Briefing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxAttemptNo = `-- name: MaxAttemptNo :one
SELECT COALESCE(max(attempt_no), 0)::int AS max_no
FROM ticket_attempts
WHERE variant_id = $1 AND user_id = $2
`

type MaxAttemptNoParams struct {
	VariantID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) MaxAttemptNo(ctx context.Context, arg MaxAttemptNoParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxAttemptNo, arg.VariantID, arg.UserID)
	var max_no int32
	err := row.Scan(&max_no)
	return max_no, err
}

const updateAttempt = `-- name: UpdateAttempt :exec
UPDATE ticket_attempts
SET status = $2, started_at = $3, deadline_at = $4, finished_at = $5, score = $6, report = $7
WHERE id = $1
`

type UpdateAttemptParams struct {
	ID         uuid.UUID
	Status     string
	StartedAt  *time.Time
	DeadlineAt *time.Time
	FinishedAt *time.Time
	Score      *int16
	Report     []byte
}

func (q *Queries) UpdateAttempt(ctx context.Context, arg UpdateAttemptParams) error {
	_, err := q.db.Exec(ctx, updateAttempt,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.DeadlineAt,
		arg.FinishedAt,
		arg.Score,
		arg.Report,
	)
	return err
}

const updateDialogSnapshot = `-- name: UpdateDialogSnapshot :execrows
UPDATE tickets SET scenario = $2, scenario_version = $3 WHERE id = $1
`

type UpdateDialogSnapshotParams struct {
	ID              uuid.UUID
	Scenario        []byte
	ScenarioVersion string
}

func (q *Queries) UpdateDialogSnapshot(ctx context.Context, arg UpdateDialogSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDialogSnapshot, arg.ID, arg.Scenario, arg.ScenarioVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTicket = `-- name: UpdateTicket :exec
UPDATE tickets SET title = $2, body = $3, topic_id = $4 WHERE id = $1
`

type UpdateTicketParams struct {
	ID      uuid.UUID
	Title   string
	Body    string
	TopicID uuid.UUID
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) error {
	_, err := q.db.Exec(ctx, updateTicket,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.TopicID,
	)
	return err
}

const upsertAttemptAnswer = `-- name: UpsertAttemptAnswer :exec
INSERT INTO attempt_answers (
    attempt_id, ticket_id, incident_type_code, applicant_last_name, applicant_first_name,
    caller_number, dictated_number, notes, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (attempt_id, ticket_id) DO UPDATE SET
    incident_type_code = EXCLUDED.incident_type_code,
    applicant_last_name = EXCLUDED.applicant_last_name,
    applicant_first_name = EXCLUDED.applicant_first_name,
    caller_number = EXCLUDED.caller_number,
    dictated_number = EXCLUDED.dictated_number,
    notes = EXCLUDED.notes,
    updated_at = EXCLUDED.updated_at
`

type UpsertAttemptAnswerParams struct {
	AttemptID          uuid.UUID
	TicketID           uuid.UUID
	IncidentTypeCode   *string
	ApplicantLastName  string
	ApplicantFirstName string
	CallerNumber       string
	DictatedNumber     string
	Notes              string
	UpdatedAt          time.Time
}

func (q *Queries) UpsertAttemptAnswer(ctx context.Context, arg UpsertAttemptAnswerParams) error {
	_, err := q.db.Exec(ctx, upsertAttemptAnswer,
		arg.AttemptID,
		arg.TicketID,
		arg.IncidentTypeCode,
		arg.ApplicantLastName,
		arg.ApplicantFirstName,
		arg.CallerNumber,
		arg.DictatedNumber,
		arg.Notes,
		arg.UpdatedAt,
	)
	return err
}

const upsertReferenceAnswer = `-- name: UpsertReferenceAnswer :exec
INSERT INTO ticket_reference_answers (
    ticket_id, incident_type_code, applicant_last_name, applicant_first_name,
    caller_number, dictated_number
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (ticket_id) DO UPDATE SET
    incident_type_code = EXCLUDED.incident_type_code,
    applicant_last_name = EXCLUDED.applicant_last_name,
    applicant_first_name = EXCLUDED.applicant_first_name,
    caller_number = EXCLUDED.caller_number,
    dictated_number = EXCLUDED.dictated_number
`

type UpsertReferenceAnswerParams struct {
	TicketID           uuid.UUID
	IncidentTypeCode   string
	ApplicantLastName  string
	ApplicantFirstName string
	CallerNumber       string
	DictatedNumber     string
}

func (q *Queries) UpsertReferenceAnswer(ctx context.Context, arg UpsertReferenceAnswerParams) error {
	_, err := q.db.Exec(ctx, upsertReferenceAnswer,
		arg.TicketID,
		arg.IncidentTypeCode,
		arg.ApplicantLastName,
		arg.ApplicantFirstName,
		arg.CallerNumber,
		arg.DictatedNumber,
	)
	return err
}
