// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package ticketssql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countFinishedAttempts = `-- name: CountFinishedAttempts :one
SELECT count(*)::int AS count
FROM ticket_attempts
WHERE ticket_id = $1 AND user_id = $2 AND status IN ('submitted', 'timed_out')
`

type CountFinishedAttemptsParams struct {
	TicketID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) CountFinishedAttempts(ctx context.Context, arg CountFinishedAttemptsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countFinishedAttempts, arg.TicketID, arg.UserID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createAttempt = `-- name: CreateAttempt :exec
INSERT INTO ticket_attempts (
    id, ticket_id, user_id, attempt_no, status, started_at, deadline_at, finished_at, score
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAttemptParams struct {
	ID         uuid.UUID
	TicketID   uuid.UUID
	UserID     uuid.UUID
	AttemptNo  int32
	Status     string
	StartedAt  time.Time
	DeadlineAt *time.Time
	FinishedAt *time.Time
	Score      *int16
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) error {
	_, err := q.db.Exec(ctx, createAttempt,
		arg.ID,
		arg.TicketID,
		arg.UserID,
		arg.AttemptNo,
		arg.Status,
		arg.StartedAt,
		arg.DeadlineAt,
		arg.FinishedAt,
		arg.Score,
	)
	return err
}

const createAttemptAnswer = `-- name: CreateAttemptAnswer :exec
INSERT INTO attempt_answers (
    attempt_id, incident_type_code, applicant_last_name, applicant_first_name,
    caller_number, dictated_number, notes, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAttemptAnswerParams struct {
	AttemptID          uuid.UUID
	IncidentTypeCode   *string
	ApplicantLastName  string
	ApplicantFirstName string
	CallerNumber       string
	DictatedNumber     string
	Notes              string
	UpdatedAt          time.Time
}

func (q *Queries) CreateAttemptAnswer(ctx context.Context, arg CreateAttemptAnswerParams) error {
	_, err := q.db.Exec(ctx, createAttemptAnswer,
		arg.AttemptID,
		arg.IncidentTypeCode,
		arg.ApplicantLastName,
		arg.ApplicantFirstName,
		arg.CallerNumber,
		arg.DictatedNumber,
		arg.Notes,
		arg.UpdatedAt,
	)
	return err
}

const createTicket = `-- name: CreateTicket :exec
INSERT INTO tickets (
    id, group_id, title, body, max_attempts,
    available_from, available_until, duration_seconds, created_by, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateTicketParams struct {
	ID              uuid.UUID
	GroupID         uuid.UUID
	Title           string
	Body            string
	MaxAttempts     *int32
	AvailableFrom   *time.Time
	AvailableUntil  *time.Time
	DurationSeconds *int32
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) error {
	_, err := q.db.Exec(ctx, createTicket,
		arg.ID,
		arg.GroupID,
		arg.Title,
		arg.Body,
		arg.MaxAttempts,
		arg.AvailableFrom,
		arg.AvailableUntil,
		arg.DurationSeconds,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteAttemptAnswerServices = `-- name: DeleteAttemptAnswerServices :exec
DELETE FROM attempt_answer_services WHERE attempt_id = $1
`

func (q *Queries) DeleteAttemptAnswerServices(ctx context.Context, attemptID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttemptAnswerServices, attemptID)
	return err
}

const deleteAttemptAnswerTags = `-- name: DeleteAttemptAnswerTags :exec
DELETE FROM attempt_answer_tags WHERE attempt_id = $1
`

func (q *Queries) DeleteAttemptAnswerTags(ctx context.Context, attemptID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttemptAnswerTags, attemptID)
	return err
}

const deleteReferenceAnswerServices = `-- name: DeleteReferenceAnswerServices :exec
DELETE FROM reference_answer_services WHERE ticket_id = $1
`

func (q *Queries) DeleteReferenceAnswerServices(ctx context.Context, ticketID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReferenceAnswerServices, ticketID)
	return err
}

const deleteReferenceAnswerTags = `-- name: DeleteReferenceAnswerTags :exec
DELETE FROM reference_answer_tags WHERE ticket_id = $1
`

func (q *Queries) DeleteReferenceAnswerTags(ctx context.Context, ticketID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReferenceAnswerTags, ticketID)
	return err
}

const findInProgressAttempt = `-- name: FindInProgressAttempt :one
SELECT id, ticket_id, user_id, attempt_no, status, started_at, deadline_at, finished_at, score
FROM ticket_attempts
WHERE ticket_id = $1 AND user_id = $2 AND status = 'in_progress'
`

type FindInProgressAttemptParams struct {
	TicketID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) FindInProgressAttempt(ctx context.Context, arg FindInProgressAttemptParams) (TicketAttempt, error) {
	row := q.db.QueryRow(ctx, findInProgressAttempt, arg.TicketID, arg.UserID)
	var i TicketAttempt
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.AttemptNo,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
		&i.Score,
	)
	return i, err
}

const getAttemptAnswer = `-- name: GetAttemptAnswer :one
SELECT attempt_id, incident_type_code, applicant_last_name, applicant_first_name,
       caller_number, dictated_number, notes, updated_at
FROM attempt_answers
WHERE attempt_id = $1
`

func (q *Queries) GetAttemptAnswer(ctx context.Context, attemptID uuid.UUID) (AttemptAnswer, error) {
	row := q.db.QueryRow(ctx, getAttemptAnswer, attemptID)
	var i AttemptAnswer
	err := row.Scan(
		&i.AttemptID,
		&i.IncidentTypeCode,
		&i.ApplicantLastName,
		&i.ApplicantFirstName,
		&i.CallerNumber,
		&i.DictatedNumber,
		&i.Notes,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttemptByID = `-- name: GetAttemptByID :one
SELECT id, ticket_id, user_id, attempt_no, status, started_at, deadline_at, finished_at, score
FROM ticket_attempts
WHERE id = $1
`

func (q *Queries) GetAttemptByID(ctx context.Context, id uuid.UUID) (TicketAttempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByID, id)
	var i TicketAttempt
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.AttemptNo,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
		&i.Score,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT member_role
FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.GroupID, arg.UserID)
	var member_role string
	err := row.Scan(&member_role)
	return member_role, err
}

const getReferenceAnswer = `-- name: GetReferenceAnswer :one
SELECT ticket_id, incident_type_code, applicant_last_name, applicant_first_name,
       caller_number, dictated_number
FROM ticket_reference_answers
WHERE ticket_id = $1
`

func (q *Queries) GetReferenceAnswer(ctx context.Context, ticketID uuid.UUID) (TicketReferenceAnswer, error) {
	row := q.db.QueryRow(ctx, getReferenceAnswer, ticketID)
	var i TicketReferenceAnswer
	err := row.Scan(
		&i.TicketID,
		&i.IncidentTypeCode,
		&i.ApplicantLastName,
		&i.ApplicantFirstName,
		&i.CallerNumber,
		&i.DictatedNumber,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, group_id, title, body, max_attempts,
       available_from, available_until, duration_seconds, created_by, created_at
FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Body,
		&i.MaxAttempts,
		&i.AvailableFrom,
		&i.AvailableUntil,
		&i.DurationSeconds,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAttemptAnswerService = `-- name: InsertAttemptAnswerService :exec
INSERT INTO attempt_answer_services (attempt_id, service_code) VALUES ($1, $2)
`

type InsertAttemptAnswerServiceParams struct {
	AttemptID   uuid.UUID
	ServiceCode string
}

func (q *Queries) InsertAttemptAnswerService(ctx context.Context, arg InsertAttemptAnswerServiceParams) error {
	_, err := q.db.Exec(ctx, insertAttemptAnswerService, arg.AttemptID, arg.ServiceCode)
	return err
}

const insertAttemptAnswerTag = `-- name: InsertAttemptAnswerTag :exec
INSERT INTO attempt_answer_tags (attempt_id, tag_code) VALUES ($1, $2)
`

type InsertAttemptAnswerTagParams struct {
	AttemptID uuid.UUID
	TagCode   string
}

func (q *Queries) InsertAttemptAnswerTag(ctx context.Context, arg InsertAttemptAnswerTagParams) error {
	_, err := q.db.Exec(ctx, insertAttemptAnswerTag, arg.AttemptID, arg.TagCode)
	return err
}

const insertReferenceAnswerService = `-- name: InsertReferenceAnswerService :exec
INSERT INTO reference_answer_services (ticket_id, service_code) VALUES ($1, $2)
`

type InsertReferenceAnswerServiceParams struct {
	TicketID    uuid.UUID
	ServiceCode string
}

func (q *Queries) InsertReferenceAnswerService(ctx context.Context, arg InsertReferenceAnswerServiceParams) error {
	_, err := q.db.Exec(ctx, insertReferenceAnswerService, arg.TicketID, arg.ServiceCode)
	return err
}

const insertReferenceAnswerTag = `-- name: InsertReferenceAnswerTag :exec
INSERT INTO reference_answer_tags (ticket_id, tag_code) VALUES ($1, $2)
`

type InsertReferenceAnswerTagParams struct {
	TicketID uuid.UUID
	TagCode  string
}

func (q *Queries) InsertReferenceAnswerTag(ctx context.Context, arg InsertReferenceAnswerTagParams) error {
	_, err := q.db.Exec(ctx, insertReferenceAnswerTag, arg.TicketID, arg.TagCode)
	return err
}

const listAttemptAnswerServices = `-- name: ListAttemptAnswerServices :many
SELECT service_code FROM attempt_answer_services WHERE attempt_id = $1
`

func (q *Queries) ListAttemptAnswerServices(ctx context.Context, attemptID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAttemptAnswerServices, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var service_code string
		if err := rows.Scan(&service_code); err != nil {
			return nil, err
		}
		items = append(items, service_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptAnswerTags = `-- name: ListAttemptAnswerTags :many
SELECT tag_code FROM attempt_answer_tags WHERE attempt_id = $1
`

func (q *Queries) ListAttemptAnswerTags(ctx context.Context, attemptID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAttemptAnswerTags, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag_code string
		if err := rows.Scan(&tag_code); err != nil {
			return nil, err
		}
		items = append(items, tag_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsByTicketUser = `-- name: ListAttemptsByTicketUser :many
SELECT id, ticket_id, user_id, attempt_no, status, started_at, deadline_at, finished_at, score
FROM ticket_attempts
WHERE ticket_id = $1 AND user_id = $2
ORDER BY attempt_no
`

type ListAttemptsByTicketUserParams struct {
	TicketID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) ListAttemptsByTicketUser(ctx context.Context, arg ListAttemptsByTicketUserParams) ([]TicketAttempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByTicketUser, arg.TicketID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketAttempt{}
	for rows.Next() {
		var i TicketAttempt
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.UserID,
			&i.AttemptNo,
			&i.Status,
			&i.StartedAt,
			&i.DeadlineAt,
			&i.FinishedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferenceAnswerServices = `-- name: ListReferenceAnswerServices :many
SELECT service_code FROM reference_answer_services WHERE ticket_id = $1
`

func (q *Queries) ListReferenceAnswerServices(ctx context.Context, ticketID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listReferenceAnswerServices, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var service_code string
		if err := rows.Scan(&service_code); err != nil {
			return nil, err
		}
		items = append(items, service_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferenceAnswerTags = `-- name: ListReferenceAnswerTags :many
SELECT tag_code FROM reference_answer_tags WHERE ticket_id = $1
`

func (q *Queries) ListReferenceAnswerTags(ctx context.Context, ticketID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listReferenceAnswerTags, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag_code string
		if err := rows.Scan(&tag_code); err != nil {
			return nil, err
		}
		items = append(items, tag_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByGroup = `-- name: ListTicketsByGroup :many
SELECT id, group_id, title, body, max_attempts,
       available_from, available_until, duration_seconds, created_by, created_at
FROM tickets
WHERE group_id = $1
ORDER BY created_at
`

func (q *Queries) ListTicketsByGroup(ctx context.Context, groupID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Body,
			&i.MaxAttempts,
			&i.AvailableFrom,
			&i.AvailableUntil,
			&i.DurationSeconds,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxAttemptNo = `-- name: MaxAttemptNo :one
SELECT COALESCE(max(attempt_no), 0)::int AS max_no
FROM ticket_attempts
WHERE ticket_id = $1 AND user_id = $2
`

type MaxAttemptNoParams struct {
	TicketID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) MaxAttemptNo(ctx context.Context, arg MaxAttemptNoParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxAttemptNo, arg.TicketID, arg.UserID)
	var max_no int32
	err := row.Scan(&max_no)
	return max_no, err
}

const updateAttempt = `-- name: UpdateAttempt :exec
UPDATE ticket_attempts
SET status = $2, finished_at = $3, score = $4
WHERE id = $1
`

type UpdateAttemptParams struct {
	ID         uuid.UUID
	Status     string
	FinishedAt *time.Time
	Score      *int16
}

func (q *Queries) UpdateAttempt(ctx context.Context, arg UpdateAttemptParams) error {
	_, err := q.db.Exec(ctx, updateAttempt,
		arg.ID,
		arg.Status,
		arg.FinishedAt,
		arg.Score,
	)
	return err
}

const updateAttemptAnswer = `-- name: UpdateAttemptAnswer :exec
UPDATE attempt_answers
SET incident_type_code = $2,
    applicant_last_name = $3,
    applicant_first_name = $4,
    caller_number = $5,
    dictated_number = $6,
    notes = $7,
    updated_at = $8
WHERE attempt_id = $1
`

type UpdateAttemptAnswerParams struct {
	AttemptID          uuid.UUID
	IncidentTypeCode   *string
	ApplicantLastName  string
	ApplicantFirstName string
	CallerNumber       string
	DictatedNumber     string
	Notes              string
	UpdatedAt          time.Time
}

func (q *Queries) UpdateAttemptAnswer(ctx context.Context, arg UpdateAttemptAnswerParams) error {
	_, err := q.db.Exec(ctx, updateAttemptAnswer,
		arg.AttemptID,
		arg.IncidentTypeCode,
		arg.ApplicantLastName,
		arg.ApplicantFirstName,
		arg.CallerNumber,
		arg.DictatedNumber,
		arg.Notes,
		arg.UpdatedAt,
	)
	return err
}

const upsertReferenceAnswer = `-- name: UpsertReferenceAnswer :exec
INSERT INTO ticket_reference_answers (
    ticket_id, incident_type_code, applicant_last_name, applicant_first_name,
    caller_number, dictated_number
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (ticket_id) DO UPDATE SET
    incident_type_code = EXCLUDED.incident_type_code,
    applicant_last_name = EXCLUDED.applicant_last_name,
    applicant_first_name = EXCLUDED.applicant_first_name,
    caller_number = EXCLUDED.caller_number,
    dictated_number = EXCLUDED.dictated_number
`

type UpsertReferenceAnswerParams struct {
	TicketID           uuid.UUID
	IncidentTypeCode   string
	ApplicantLastName  string
	ApplicantFirstName string
	CallerNumber       string
	DictatedNumber     string
}

func (q *Queries) UpsertReferenceAnswer(ctx context.Context, arg UpsertReferenceAnswerParams) error {
	_, err := q.db.Exec(ctx, upsertReferenceAnswer,
		arg.TicketID,
		arg.IncidentTypeCode,
		arg.ApplicantLastName,
		arg.ApplicantFirstName,
		arg.CallerNumber,
		arg.DictatedNumber,
	)
	return err
}
