-- +goose Up
-- Owner-executor bank/calls owned by traineebox (AD-1/AD-2/AD-8).
-- Additive only: no DROP of legacy tables (ponytail: drop after dual-read verified).

CREATE TABLE IF NOT EXISTS dialog_slots (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'value' CHECK (kind IN ('value', 'yesno', 'description')),
    family TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS slot_questions (
    slot_id TEXT NOT NULL REFERENCES dialog_slots(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (slot_id, question)
);
CREATE INDEX IF NOT EXISTS slot_questions_slot_idx ON slot_questions(slot_id);

-- Single-writer bank state: one row per version, immutable snapshots.
-- In-flight calls finish on old digest (AD-8); hot call path never hits DB.
CREATE TABLE IF NOT EXISTS bank_state (
    version TEXT PRIMARY KEY,
    digest TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Ticket dialog snapshot (canon lives here; dialog rejects drift with 400 AD-7).
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS scenario JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS scenario_version TEXT NOT NULL DEFAULT '';
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS reference JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS mode TEXT NOT NULL DEFAULT 'voice' CHECK (mode IN ('voice', 'text', 'both'));
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS briefing TEXT NOT NULL DEFAULT '';

-- call_id = attempt_calls.id = session_id = AudioSocket UUID (AD-6), generated by traineebox.
CREATE TABLE IF NOT EXISTS attempt_calls (
    id UUID PRIMARY KEY,
    attempt_id UUID NOT NULL REFERENCES ticket_attempts(id) ON DELETE CASCADE,
    ticket_id UUID NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scenario_id TEXT NOT NULL DEFAULT '',
    bank_digest TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'originating'
        CHECK (status IN ('originating', 'ringing', 'answered', 'completed', 'no_answer', 'failed', 'timed_out')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS attempt_calls_attempt_idx ON attempt_calls(attempt_id);
CREATE INDEX IF NOT EXISTS attempt_calls_ticket_user_idx ON attempt_calls(ticket_id, user_id);

-- Turns only (no wav upload to traineebox; wav stays on dialog volume).
CREATE TABLE IF NOT EXISTS call_turns (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    call_id UUID NOT NULL REFERENCES attempt_calls(id) ON DELETE CASCADE,
    n INT NOT NULL CHECK (n > 0),
    utterance TEXT NOT NULL DEFAULT '',
    reply TEXT NOT NULL DEFAULT '',
    style TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (call_id, n)
);
CREATE INDEX IF NOT EXISTS call_turns_call_idx ON call_turns(call_id);

-- SIP endpoints owned by traineebox; Asterisk reads via realtime VIEWs.
-- No reload on user create: Asterisk realtime hits these VIEWs directly.
CREATE TABLE IF NOT EXISTS user_sip_endpoints (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- PJSIP realtime VIEWs (Asterisk sorcery/res_config). Only enabled rows register.
CREATE OR REPLACE VIEW ps_endpoints AS
SELECT
    endpoint AS id,
    'transport-udp' AS transport,
    endpoint AS aors,
    endpoint AS auth,
    'trainer-out' AS context,
    'all' AS disallow,
    'alaw' AS allow,
    'no' AS direct_media,
    'yes' AS force_rport,
    'yes' AS rewrite_contact,
    endpoint AS callerid
FROM user_sip_endpoints
WHERE enabled;

CREATE OR REPLACE VIEW ps_auths AS
SELECT
    endpoint AS id,
    'userpass' AS auth_type,
    endpoint AS username,
    password_hash AS password
FROM user_sip_endpoints
WHERE enabled;

CREATE OR REPLACE VIEW ps_aors AS
SELECT
    endpoint AS id,
    2 AS max_contacts,
    'yes' AS remove_existing
FROM user_sip_endpoints
WHERE enabled;

-- Asterisk realtime SELECT grants live in the initializer ensure step
-- (cmd/initializer/migrate.go): goose's splitter breaks on $$ blocks,
-- the server parses them fine as one Go string.

-- +goose Down
DROP VIEW IF EXISTS ps_aors;
DROP VIEW IF EXISTS ps_auths;
DROP VIEW IF EXISTS ps_endpoints;
DROP TABLE IF EXISTS user_sip_endpoints;
DROP TABLE IF EXISTS call_turns;
DROP TABLE IF EXISTS attempt_calls;
ALTER TABLE tickets DROP COLUMN IF EXISTS briefing;
ALTER TABLE tickets DROP COLUMN IF EXISTS mode;
ALTER TABLE tickets DROP COLUMN IF EXISTS reference;
ALTER TABLE tickets DROP COLUMN IF EXISTS scenario_version;
ALTER TABLE tickets DROP COLUMN IF EXISTS scenario;
DROP TABLE IF EXISTS bank_state;
DROP TABLE IF EXISTS slot_questions;
DROP TABLE IF EXISTS dialog_slots;
