// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dialogsql

import (
	"time"
)

type BankState struct {
	Version   string
	Digest    string
	UpdatedAt time.Time
}

type DialogSlot struct {
	ID     string
	Label  string
	Kind   string
	Family string
}

type SlotQuestion struct {
	SlotID   string
	Question string
	Source   string
}
