// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package dialogsql

import (
	"context"
)

const bankVersion = `-- name: BankVersion :one
SELECT version, digest FROM bank_state ORDER BY updated_at DESC LIMIT 1
`

type BankVersionRow struct {
	Version string
	Digest  string
}

func (q *Queries) BankVersion(ctx context.Context) (BankVersionRow, error) {
	row := q.db.QueryRow(ctx, bankVersion)
	var i BankVersionRow
	err := row.Scan(&i.Version, &i.Digest)
	return i, err
}

const listSlotIDs = `-- name: ListSlotIDs :many
SELECT id FROM dialog_slots
`

func (q *Queries) ListSlotIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSlotIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
