// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package authsql

import (
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Login        string
	PasswordHash string
	Role         string
	FullName     string
	BlockedAt    *time.Time
	CreatedAt    time.Time
}
