package calls

import (
	"time"

	"github.com/google/uuid"
)

// Call owns voice execution (AD-9). call_id = attempt_calls.id = session_id
// = AudioSocket UUID, generated by traineebox. Only system originates (ARI);
// student voice sees only {attempt_id, deadline}.
type Call struct {
	ID         uuid.UUID
	AttemptID  uuid.UUID
	TicketID   uuid.UUID
	UserID     uuid.UUID
	ScenarioID string
	BankDigest string
	ChannelID  string // ARI channel id from originate (real hangup target; spec F)
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

const (
	StatusOriginating = "originating"
	StatusRinging     = "ringing"
	StatusAnswered    = "answered"
	StatusCompleted   = "completed"
	StatusNoAnswer    = "no_answer"
	StatusFailed      = "failed"
	StatusTimedOut    = "timed_out"
)

// Answered blocks recall: repeat `call` after answered/completed → 409.
func (c Call) BlocksRecall() bool {
	return c.Status == StatusAnswered || c.Status == StatusCompleted ||
		c.Status == StatusRinging || c.Status == StatusOriginating
}

type Turn struct {
	N         int
	Utterance string
	Reply     string
	Style     string
}
