// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package groupssql

import (
	"time"

	"github.com/google/uuid"
)

type Group struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type GroupMember struct {
	GroupID    uuid.UUID
	UserID     uuid.UUID
	MemberRole string
	JoinedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Role      string
	BlockedAt *time.Time
}
