// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package groupssql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :exec
INSERT INTO groups (id, name, created_at)
VALUES ($1, $2, $3)
`

type CreateGroupParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.Exec(ctx, createGroup, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const createGroupMember = `-- name: CreateGroupMember :exec
INSERT INTO group_members (group_id, user_id, member_role, joined_at)
VALUES ($1, $2, $3, $4)
`

type CreateGroupMemberParams struct {
	GroupID    uuid.UUID
	UserID     uuid.UUID
	MemberRole string
	JoinedAt   time.Time
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) error {
	_, err := q.db.Exec(ctx, createGroupMember,
		arg.GroupID,
		arg.UserID,
		arg.MemberRole,
		arg.JoinedAt,
	)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups
WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
DELETE FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type DeleteGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) error {
	_, err := q.db.Exec(ctx, deleteGroupMember, arg.GroupID, arg.UserID)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, role, blocked_at
FROM users
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Role, &i.BlockedAt)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, created_at
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listAllGroups = `-- name: ListAllGroups :many
SELECT id, name, created_at
FROM groups
ORDER BY created_at
`

func (q *Queries) ListAllGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupIDsByMember = `-- name: ListGroupIDsByMember :many
SELECT group_id
FROM group_members
WHERE user_id = $1
`

func (q *Queries) ListGroupIDsByMember(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listGroupIDsByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var group_id uuid.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT group_id, user_id, member_role, joined_at
FROM group_members
WHERE group_id = $1
ORDER BY joined_at
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMember{}
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.MemberRole,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupName = `-- name: UpdateGroupName :exec
UPDATE groups
SET name = $2
WHERE id = $1
`

type UpdateGroupNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateGroupName(ctx context.Context, arg UpdateGroupNameParams) error {
	_, err := q.db.Exec(ctx, updateGroupName, arg.ID, arg.Name)
	return err
}
