// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package generationsql

import (
	"time"

	"github.com/google/uuid"
)

type Group struct {
	ID uuid.UUID
}

type Ticket struct {
	ID uuid.UUID
}

type TicketGenerationJob struct {
	ID                uuid.UUID
	GroupID           uuid.UUID
	CreatedBy         uuid.UUID
	Prompt            string
	Status            string
	Version           int32
	ScenarioText      string
	DraftTitle        string
	DraftReference    []byte
	ErrorMessage      string
	Attempts          int32
	PublishedTicketID *uuid.UUID
	ClaimedBy         string
	ClaimedAt         *time.Time
	LeaseUntil        *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type User struct {
	ID uuid.UUID
}
