// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package generationsql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGenerationJob = `-- name: CreateGenerationJob :exec
INSERT INTO ticket_generation_jobs (
    id, group_id, created_by, prompt, status, version,
    scenario_text, draft_title, draft_reference, error_message, attempts,
    published_ticket_id, claimed_by, claimed_at, lease_until, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17
)
`

type CreateGenerationJobParams struct {
	ID                uuid.UUID
	GroupID           uuid.UUID
	CreatedBy         uuid.UUID
	Prompt            string
	Status            string
	Version           int32
	ScenarioText      string
	DraftTitle        string
	DraftReference    []byte
	ErrorMessage      string
	Attempts          int32
	PublishedTicketID *uuid.UUID
	ClaimedBy         string
	ClaimedAt         *time.Time
	LeaseUntil        *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) CreateGenerationJob(ctx context.Context, arg CreateGenerationJobParams) error {
	_, err := q.db.Exec(ctx, createGenerationJob,
		arg.ID,
		arg.GroupID,
		arg.CreatedBy,
		arg.Prompt,
		arg.Status,
		arg.Version,
		arg.ScenarioText,
		arg.DraftTitle,
		arg.DraftReference,
		arg.ErrorMessage,
		arg.Attempts,
		arg.PublishedTicketID,
		arg.ClaimedBy,
		arg.ClaimedAt,
		arg.LeaseUntil,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteGenerationJob = `-- name: DeleteGenerationJob :exec
DELETE FROM ticket_generation_jobs WHERE id = $1
`

func (q *Queries) DeleteGenerationJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGenerationJob, id)
	return err
}

const getGenerationJobByID = `-- name: GetGenerationJobByID :one
SELECT
    id, group_id, created_by, prompt, status, version,
    scenario_text, draft_title, draft_reference, error_message, attempts,
    published_ticket_id, claimed_by, claimed_at, lease_until, created_at, updated_at
FROM ticket_generation_jobs
WHERE id = $1
`

func (q *Queries) GetGenerationJobByID(ctx context.Context, id uuid.UUID) (TicketGenerationJob, error) {
	row := q.db.QueryRow(ctx, getGenerationJobByID, id)
	var i TicketGenerationJob
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.Prompt,
		&i.Status,
		&i.Version,
		&i.ScenarioText,
		&i.DraftTitle,
		&i.DraftReference,
		&i.ErrorMessage,
		&i.Attempts,
		&i.PublishedTicketID,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGenerationJobsByGroup = `-- name: ListGenerationJobsByGroup :many
SELECT
    id, group_id, created_by, prompt, status, version,
    scenario_text, draft_title, draft_reference, error_message, attempts,
    published_ticket_id, claimed_by, claimed_at, lease_until, created_at, updated_at
FROM ticket_generation_jobs
WHERE group_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListGenerationJobsByGroup(ctx context.Context, groupID uuid.UUID) ([]TicketGenerationJob, error) {
	rows, err := q.db.Query(ctx, listGenerationJobsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketGenerationJob{}
	for rows.Next() {
		var i TicketGenerationJob
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.Prompt,
			&i.Status,
			&i.Version,
			&i.ScenarioText,
			&i.DraftTitle,
			&i.DraftReference,
			&i.ErrorMessage,
			&i.Attempts,
			&i.PublishedTicketID,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.LeaseUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenerationJobCAS = `-- name: UpdateGenerationJobCAS :execrows
UPDATE ticket_generation_jobs SET
    status = $1,
    version = version + 1,
    scenario_text = $2,
    draft_title = $3,
    draft_reference = $4,
    error_message = $5,
    attempts = $6,
    published_ticket_id = $7,
    claimed_by = $8,
    claimed_at = $9,
    lease_until = $10,
    updated_at = $11
WHERE id = $12
  AND status = $13
  AND version = $14
`

type UpdateGenerationJobCASParams struct {
	Status            string
	ScenarioText      string
	DraftTitle        string
	DraftReference    []byte
	ErrorMessage      string
	Attempts          int32
	PublishedTicketID *uuid.UUID
	ClaimedBy         string
	ClaimedAt         *time.Time
	LeaseUntil        *time.Time
	UpdatedAt         time.Time
	ID                uuid.UUID
	Status_2          string
	Version           int32
}

func (q *Queries) UpdateGenerationJobCAS(ctx context.Context, arg UpdateGenerationJobCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGenerationJobCAS,
		arg.Status,
		arg.ScenarioText,
		arg.DraftTitle,
		arg.DraftReference,
		arg.ErrorMessage,
		arg.Attempts,
		arg.PublishedTicketID,
		arg.ClaimedBy,
		arg.ClaimedAt,
		arg.LeaseUntil,
		arg.UpdatedAt,
		arg.ID,
		arg.Status_2,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
